[package]
name = "curve_plots"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3.5"
curv-kzen = "0.10"
num-complex = "0.4"